# Import necessary libraries
import streamlit as st
import streamlit.components.v1 as components
import pandas as pd
import os

# -----------------------------------------------------------------------------
# 1. PAGE CONFIGURATION
# This must be the first Streamlit command in your script.
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Rulin Waishi - A Spatial Analysis",
    page_icon="🗺️",  # You can use an emoji as the page icon
    layout="wide"
)

# -----------------------------------------------------------------------------
# 2. TITLE AND INTRODUCTION
# Use st.title, st.header, st.subheader, or st.markdown for text.
# -----------------------------------------------------------------------------
st.title("A Spatial Analysis of *The Scholars* (儒林外史)")
st.subheader("Visualizing Key Locations in the First 20 Chapters")

st.markdown("""
This interactive web application presents a spatial analysis of key cities mentioned in the classic Chinese novel *Rulin Waishi* (The Scholars). 
The map below visualizes the frequency of mentions for five major cities within the first 20 chapters of the text.

**How to interact with the map:**
- **Click** on the red circles to view the city's name and its mention frequency.
- **Pan and zoom** to explore the geographical context.

This project utilizes a Digital Humanities workflow:
- **Data Source**: *Rulin Waishi* text from Ctext.org, geographical data from CHGIS.
- **Tools**: Python for data extraction, QGIS for map creation, and Streamlit for web deployment.
""")

# A horizontal line to separate sections
st.divider()

# -----------------------------------------------------------------------------
# 3. INTERACTIVE MAP
# We will embed the HTML map generated by qgis2web here.
# -----------------------------------------------------------------------------
st.header("Interactive Frequency Map")

map_url = "https://josiczhou.github.io/chc5904-assignment2/qgis2web/"
st.components.v1.iframe(map_url, height=650, scrolling=True)

st.divider()

# -----------------------------------------------------------------------------
# 4. DATA TABLE DISPLAY
# Displaying the underlying data adds transparency to your analysis.
# -----------------------------------------------------------------------------
st.header("Underlying Data")
st.markdown("The following table contains the raw data used to generate the map visualization.")

# Define the path to your data file
data_path = 'qgis_data.csv'

if os.path.exists(data_path):
    # Read the data using pandas
    df = pd.read_csv(data_path)
    # Display the data as an interactive table
    st.dataframe(df)
else:
    st.warning(f"Warning: Data file not found at '{data_path}'. The data table cannot be displayed.")


